name: Terraform Deploy AWS EC2

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env: # 👈 ENV a nivel del job completo
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform -chdir=infra/terraform init

      - name: Terraform Validate
        run: terraform -chdir=infra/terraform validate

      - name: Terraform Plan
        run: terraform -chdir=infra/terraform plan

      - name: Terraform Apply
        run: terraform -chdir=infra/terraform apply -auto-approve
